hackzurich/challenge/models.py
# -*- coding: utf-8 -*-
"""Challenge models."""
import datetime as dt


from hackzurich.database import (
    Column,
    PkModel,
    db,
    reference_col,
    relationship,
)
from hackzurich.extensions import bcrypt


class Company(PkModel):
    __tablename__ = "company"

    name = Column(db.String(80), unique=True, nullable=False)
    description = Column(db.String(500), nullable=True)
    challenges = relationship("Challenge", backref="company")

    def __init__(self, name, description, **kwargs):
        """Create instance."""
        super().__init__(name=name, description=description, **kwargs)


class User_Challenge_Association(PkModel):
    __tablename__ = "user_challenge_association"

    user_id = Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    challenge_id = Column(db.Integer, db.ForeignKey("challenges.id"), nullable=False)
    commited_to_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    done_at = Column(db.DateTime, nullable=True)
    succeeded = Column(db.Boolean, nullable=False, default=False)
    challenges = relationship("Challenge", backref="user_challenges")
    users = relationship("User", backref="user_challenges")

    def __init__(self, user_id, challenge_id, **kwargs):
        super().__init__(user_id=user_id, challenge_id=challenge_id, **kwargs)


class Category(PkModel):
    """A role for a challenge."""

    __tablename__ = "category"
    name = Column(db.String(80), unique=True, nullable=False)
    parent_id = Column(db.Integer, db.ForeignKey("category.id"), nullable=True)
    challenges = relationship("Challenge", backref="category")

    def __init__(self, name, parent_id, **kwargs):
        """Create instance."""
        super().__init__(name=name, parent_id=parent_id, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return f"<Category({self.name})>"


class Challenge(PkModel):
    """A challenge of the app."""

    __tablename__ = "challenges"
    challengename = Column(db.String(80), unique=True, nullable=False)
    description = Column(db.String(3000), nullable=False)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    active = Column(db.Boolean(), default=False)
    category_id = Column(db.Integer, db.ForeignKey("category.id"))
    company_id = Column(db.Integer, db.ForeignKey("company.id"))
    co2offset = Column(db.Integer, nullable=False)
    chat_room_id = Column(db.String, db.ForeignKey("chat_rooms.room_id"))

    def __init__(
        self, challengename, description, active, category_id, co2offset, **kwargs
    ):
        """Create instance."""
        super().__init__(
            challengename=challengename,
            description=description,
            active=active,
            category_id=category_id,
            co2offset=co2offset,
            **kwargs,
        )

    def __repr__(self):
        """Represent instance as a unique string."""
        return f"<Challenge({self.challengename!r})>"

hackzurich/challenge/views.py
# -*- coding: utf-8 -*-
"""Challenge views."""
import csv
from random import choice
from datetime import datetime, timedelta
import datetime as dt
from hackzurich.utils import flash_errors
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    redirect,
    render_template,
    url_for,
)
from flask_login import login_required, current_user
from .forms import ChallengeForm
from .models import Challenge, User_Challenge_Association, Company
from hackzurich.user.models import User
from hackzurich.database import db
import babel
from hackzurich.chat.models import ChatRoom, ChatMessage


blueprint = Blueprint(
    "challenge_blueprint", __name__, url_prefix="/challenges", static_folder="../static"
)


@blueprint.route("/<int:challenge_id>")
@login_required
def challenge(challenge_id):
    challenge = Challenge.query.filter_by(id=challenge_id).first()
    company = Company.query.filter_by(id=challenge.company_id).first()
    challenge.company = company

    user_challenge_association = (
        User_Challenge_Association.query.filter_by(
            user_id=current_user.id, challenge_id=challenge.id, done_at=None
        )
        .order_by(User_Challenge_Association.commited_to_at.asc())
        .first()
    )

    streak = (
        User_Challenge_Association.query.filter_by(
            user_id=current_user.id, challenge_id=challenge.id, succeeded=True
        )
        .order_by(User_Challenge_Association.commited_to_at.desc())
        .all()
    )

    if len(streak) > 1:
        # cut off streak
        cut_off_date = datetime(*streak[0].done_at.timetuple()[:3])
        for user_challenge_association_streak in streak[1:]:
            if (
                datetime(*user_challenge_association_streak.done_at.timetuple()[:3])
                + timedelta(days=1)
                == cut_off_date
            ):
                cut_off_date = datetime(
                    *user_challenge_association_streak.done_at.timetuple()[:3]
                )
            elif (
                datetime(*user_challenge_association_streak.done_at.timetuple()[:3])
                == cut_off_date
            ):
                cut_off_date = datetime(
                    *user_challenge_association_streak.done_at.timetuple()[:3]
                )

            else:
                break

        streak = [s for s in streak if s.done_at > cut_off_date]

    total_co2offset = (
        User_Challenge_Association.query.filter_by(challenge_id=challenge.id).count()
        * challenge.co2offset
    )

    co2offset_by_you = (
        User_Challenge_Association.query.filter_by(
            challenge_id=challenge.id, user_id=current_user.id
        ).count()
        * challenge.co2offset
    )

    with open("co2data/co2clean.csv") as csvfile:
        reader = csv.reader(csvfile)
        country_co2_csv = {rows[0]: rows[1] for rows in reader}

    with open("co2data/foodco2.csv") as csvfile:
        reader = csv.reader(csvfile)
        food_co2_csv = [{'title': rows[1], 'co2': rows[2]} for rows in reader]

    recipe = choice(food_co2_csv)

    country_total_co2 = country_co2_csv[current_user.country]

    done_user_challenges = User_Challenge_Association.query.filter_by(
        user_id=current_user.id, succeeded=True
    ).all()

    done_challenges = []
    total_saved_co2 = 0
    for done_user_challenge in done_user_challenges:
        done_user_challenge.challenge = Challenge.query.filter_by(
            id=done_user_challenge.challenge_id
        ).first()
        done_challenges.append(done_user_challenge)
        total_saved_co2 += done_user_challenge.challenge.co2offset

    return render_template(
        "challenges/challenges.html",
        challenge=challenge,
        user_challenge_association=user_challenge_association,
        streak=streak,
        done_challenges=done_challenges,
        total_co2offset=total_co2offset,
        total_saved_co2=float(total_saved_co2),
        co2offset_by_you=co2offset_by_you,
        country_total_co2=float(country_total_co2),
        recipe=recipe
    )


@blueprint.route("/create_new/", methods=["GET", "POST"])
@login_required
def create_new():
    form = ChallengeForm(request.form)
    if form.validate_on_submit():
        Challenge.create(
            challengename=form.challengename.data,
            description=form.description.data,
            active=form.active.data,
        )
        flash("You've successfully created challenge ", str(form.challengename.data))
        return redirect(url_for("user_blueprint.members"))
    else:
        flash_errors(form)
    return render_template("challenges/create_new.html", form=form)


@blueprint.route("/mark_failed/<int:challenge_id>")
@login_required
def mark_failed(challenge_id):
    challenge = Challenge.query.filter_by(id=challenge_id).first()

    user_challenge_association = (
        User_Challenge_Association.query.filter_by(
            user_id=current_user.id, challenge_id=challenge.id
        )
        .order_by(User_Challenge_Association.commited_to_at.desc())
        .first()
    )
    user_challenge_association.done_at = dt.datetime.now()
    user_challenge_association.succeeded = False
    db.session.commit()

    flash(
        "You've aborted challenge "
        + str(challenge.challengename)
        + " "
        + str(user_challenge_association.id)
    )

    return redirect(url_for("challenge_blueprint.challenge", challenge_id=challenge_id))


@blueprint.route("/mark_done/<int:challenge_id>")
@login_required
def mark_done(challenge_id):
    challenge = Challenge.query.filter_by(id=challenge_id).first()

    user_challenge_association = (
        User_Challenge_Association.query.filter_by(
            user_id=current_user.id, challenge_id=challenge.id
        )
        .order_by(User_Challenge_Association.commited_to_at.desc())
        .first()
    )
    user_challenge_association.done_at = dt.datetime.now()
    user_challenge_association.succeeded = True
    db.session.commit()

    # notify chat about success
    admin = User.query.filter_by(id=1).first()
    chat_room = ChatRoom.query.filter_by(room_id=challenge.challengename).first()
    chat_message = ChatMessage.create(
        user=admin,
        text="Congrats! "
        + current_user.username
        + " has successfully solved this challenge!",
        room=chat_room,
    )
    #  datetime(*user_challenge_association_streak.done_at.timetuple()[:3])
    # check if it has been done five times today
    count_challenges_solved_today = (
        User_Challenge_Association.query.filter_by(challenge_id=challenge.id)
        .filter(
            User_Challenge_Association.commited_to_at
            <= datetime(*datetime.now().timetuple()[:3])
        )
        .filter(User_Challenge_Association.done_at != None)
        .count()
    )

    if count_challenges_solved_today % 5 == 0:
        company = Company.query.filter_by(id=challenge.company_id).first()
        chat_message = ChatMessage.create(
            user=admin,
            text="It has been solved "
            + str(count_challenges_solved_today)
            + " times so far! That means "
            + str(company.name)
            + " is doubling the amount of saved CO2 by this challenge for today!",
            room=chat_room,
        )

    return redirect(url_for("challenge_blueprint.challenge", challenge_id=challenge_id))


@blueprint.route("/commit/<int:challenge_id>")
@login_required
def commit(challenge_id):
    challenge = Challenge.query.filter_by(id=challenge_id).first()
    user = current_user

    user_challenge_association = User_Challenge_Association.create(
        user_id=user.id, challenge_id=challenge.id
    )

    # notify chat about success
    admin = User.query.filter_by(id=1).first()
    chat_room = ChatRoom.query.filter_by(room_id=challenge.challengename).first()
    chat_message = ChatMessage.create(
        user=admin,
        text=current_user.username + " has committed to this challenge. Good luck!",
        room=chat_room,
    )

    return redirect(url_for("challenge_blueprint.challenge", challenge_id=challenge_id))

hackzurich/company/views.py
# -*- coding: utf-8 -*-
"""Challenge views."""
import csv
from datetime import datetime, timedelta
import datetime as dt
from hackzurich.utils import flash_errors
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    redirect,
    render_template,
    url_for,
)
from flask_login import login_required, current_user
from hackzurich.challenge.models import Challenge, User_Challenge_Association, Company
from hackzurich.database import db
import babel


blueprint = Blueprint(
    "company_blueprint", __name__, url_prefix="/companies", static_folder="../static"
)


@blueprint.route("/<int:company_id>")
@login_required
def display(company_id):
    company = Company.query.filter_by(id=company_id).first()

    with open("co2data/co2clean.csv") as csvfile:
        reader = csv.reader(csvfile)
        country_co2_csv = {rows[0]: rows[1] for rows in reader}
    country_total_co2 = country_co2_csv[current_user.country]

    done_user_challenges = User_Challenge_Association.query.filter_by(
        user_id=current_user.id, succeeded=True
    ).all()

    done_challenges = []
    total_saved_co2 = 0
    for done_user_challenge in done_user_challenges:
        done_user_challenge.challenge = Challenge.query.filter_by(
            id=done_user_challenge.challenge_id
        ).first()
        done_challenges.append(done_user_challenge)
        total_saved_co2 += done_user_challenge.challenge.co2offset

    return render_template(
        "companies/company.html",
        company=company,
        country_total_co2=float(country_total_co2),
        total_saved_co2=float(total_saved_co2),
    )

hackzurich/templates/challenges/challenges.html
{% extends "two_column.html" %}

{% block right_side %}
<div class="col-lg-4 col-m-6" style="margin-top: 50px;padding-left: 3%;padding-right: 3%">
    <div class="container" style="margin-bottom: 50px;margin-top: 50px;border: 1px solid;border-color: #111;padding: 10px;background: #fff">
        <h1>{{ challenge.challengename }}</h1>
        <div style="text-align: right;margin-bottom: 40px;margin-top: 20px">
            <h3>sponsored by <a href="{{ url_for('company_blueprint.display', company_id=challenge.company.id) }}">{{ challenge.company.name }}</a></h3>
        </div>

        <div id="accordion2">
          <div class="card">
            <div class="card-header" id="headingOne">
              <h5 class="mb-0">
                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseDetails" aria-expanded="true" aria-controls="collapseDetails" style="color: #000">
                  Challenge Details
                </button>
              </h5>
            </div>

            <div id="collapseDetails" class="collapse" aria-labelledby="headingOne" data-parent="#accordion2">
              <div class="card-body" style="margin-left: 10% ">
                <p>{{ challenge.description|safe }}</p>
                {% if challenge.id == 6 %}
                <p><a href="https://duckduckgo.com/?q={{recipe['title']|replace(' ', '+')}}&iax=images&ia=images">{{recipe['title']}}</a><br>because it typically only uses {{ recipe['co2']}} g of CO<sub>2</sub> per serving.</p><br>
                {% endif %}
                <div style="text-align: right">
                    <p>Saving potential: <b>{{ challenge.co2offset|round(3) }}</b> kg CO<sub>2</sub></p>
                    <p>All participants in this challenge: <b>{{ total_co2offset|round(2) }}</b> kg CO<sub>2</sub></p>
                    <p>Saved by you: <b>{{ co2offset_by_you|round(2) }}</b> kg CO<sub>2</sub></p>
                </div>
                {% if user_challenge_association != None %}
                {% if user_challenge_association.succeeded == 0 %}
                <p>Committed to this challenge since {{ user_challenge_association.commited_to_at | datetime}}</p>
                {% else %}
                <p>Challenge cancelled at {{ user_challenge_association.done_at }}</p>
                {% endif %}
                {% endif %}

                <br>
                {% if streak %}<b>Your current streak</b><br>{% endif %}
                <ul class="timeline">
                    {% for streak_association in streak %}
                    <li style="margin-left: 30px">
                        {{ streak_association.done_at | datetime }}
                    </li>
                    {% endfor %}
                </ul>
              </div>
            </div>
          </div>
          <div class="row" style="margin-top: 25px; margin-bottom: 20px">
              <div class="col" style="text-align: center">
                  <p><a href="{{ url_for('challenge_blueprint.commit', challenge_id=challenge.id) }}" class="btn btn-primary btn-large
                  {% if user_challenge_association != None %}
                  disabled
                  {% endif %}
                  ">Commit</a></p>
              </div>
              <div class="col" style="text-align: center">
                  <p><a href="{{ url_for('challenge_blueprint.mark_done', challenge_id=challenge.id) }}" class="btn btn-primary btn-large
                  {% if user_challenge_association == None %}
                  disabled
                  {% endif %}
                  ">Completed</a></p>
              </div>
              <div class="col" style="text-align: center">
                  <p><a href="{{ url_for('challenge_blueprint.mark_failed', challenge_id=challenge.id) }}" class="btn btn-primary btn-large btn-danger
                  {% if user_challenge_association == None %}
                  disabled
                  {% endif %}
                  ">Abort</a></p>
              </div>
          </div>
        </div>
        <section class="msger">
          <header class="msger-header">
            <div class="msger-header-title">
              <i class="fas fa-comment-alt"></i>Team Chat
            </div>
            <div class="msger-header-options">
              <span><i class="fas fa-cog"></i></span>
            </div>
          </header>
          <main class="msger-chat">
          </main>

          <form class="msger-inputarea">
            <input type="text" class="msger-input" placeholder="Enter your message...">
            <button type="submit" class="msger-send-btn">Send</button>
          </form>
        </section>
    </div>
</div>
{% endblock %}

{% block js %}

<script type="application/javascript">
    var socket = connect_to_socketio({{ challenge.id }});

    socket.on('join_room', function(data){
        data['history'].forEach(function(msg){
            appendMessage(msg);
        });
    });

    socket.on('new_message', function(msg){
        appendMessage(msg);
    });

    const msgerForm = get(".msger-inputarea");
    const msgerInput = get(".msger-input");
    const msgerChat = get(".msger-chat");

    // Icons made by Freepik from www.flaticon.com
    const BOT_IMG = "https://www.flaticon.com/svg/static/icons/svg/3175/3175232.svg";
    const PERSON_IMG = "https://www.flaticon.com/svg/static/icons/svg/3175/3175239.svg";
    const BOT_NAME = "BOT";
    const PERSON_NAME = "Sajad";

    msgerForm.addEventListener("submit", event => {
      event.preventDefault();

      const msgText = msgerInput.value;
      if (!msgText) return;

      msgerInput.value = "";
      socket.emit('send_message', {'text': msgText, 'challenge_id': {{ challenge.id }} });
    });

    function appendMessage(msg) {

      if (msg['is_self']){
        var img = PERSON_IMG;
        var side = 'right';

      } else {
        var img = BOT_IMG;
        var side = 'left';
      }
      //   Simple solution for small apps
      const msgHTML = `
        <div class="msg ${side}-msg">
          <div class="msg-img" style="background-image: url(${img})"></div>

          <div class="msg-bubble">
            <div class="msg-info">
              <div class="msg-info-name">${msg['user']}</div>
              <div class="msg-info-time">${formatDate(new Date(msg['written_at']))}</div>
            </div>

            <div class="msg-text">${msg['text']}</div>
          </div>
        </div>
      `;

      msgerChat.insertAdjacentHTML("beforeend", msgHTML);
      msgerChat.scrollTop += 500;
    }

    // Utils
    function get(selector, root = document) {
      return root.querySelector(selector);
    }

    function formatDate(date) {
      const h = "0" + date.getHours();
      const m = "0" + date.getMinutes();

      return `${h.slice(-2)}:${m.slice(-2)}`;
    }

</script>
{% endblock %}