hackzurich/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from hackzurich.challenge.models import Challenge, User_Challenge_Association
import csv

blueprint = Blueprint(
    "user_blueprint", __name__, url_prefix="/users", static_folder="../static"
)


@blueprint.route("/")
@login_required
def members():
    """List members."""
    active_challenges = Challenge.query.filter_by(active=True).all()
    done_user_challenges = User_Challenge_Association.query.filter_by(
        user_id=current_user.id, succeeded=True
    ).all()

    done_challenges = []
    total_saved_co2 = 0
    for done_user_challenge in done_user_challenges:
        done_user_challenge.challenge = Challenge.query.filter_by(
            id=done_user_challenge.challenge_id
        ).first()
        done_challenges.append(done_user_challenge)
        total_saved_co2 += done_user_challenge.challenge.co2offset

    for active_challenge in active_challenges:
        user_challenge_association = (
            User_Challenge_Association.query.filter_by(
                user_id=current_user.id, challenge_id=active_challenge.id
            )
            .order_by(User_Challenge_Association.commited_to_at.desc())
            .first()
        )
        active_challenge.user_challenge_association = user_challenge_association

        active_challenge.total_participants = (
            User_Challenge_Association.query.distinct(
                User_Challenge_Association.user_id
            )
            .filter_by(challenge_id=active_challenge.id)
            .count()
        )

    with open("co2data/co2clean.csv") as csvfile:
        reader = csv.reader(csvfile)
        country_co2_csv = {rows[0]: rows[1] for rows in reader}

    country_total_co2 = float(country_co2_csv[current_user.country])

    return render_template(
        "users/members.html",
        active_challenges=active_challenges,
        done_challenges=done_challenges,
        total_saved_co2=total_saved_co2,
        country_total_co2=country_total_co2,
    )

hackzurich/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public_blueprint.home')}}">log in</a> or
            <a href="{{ url_for('public_blueprint.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

hackzurich/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Dream Team: Join In</li>
  </ul>

    <ul class="footer-nav">
    </ul>
  </small>
</footer>

hackzurich/templates/layout.html
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
  <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <link rel="shortcut icon" href="{{static_url_for('static', filename='build/img/logo.png') }}" type="image/png" />

    <title>
      {% block page_title %}
      JoinIN
       {% endblock %}
    </title>
    <meta
      name="description"
      content="{% block meta_description %}{% endblock %}"
    />
    <meta name="author" content="{% block meta_author %}{% endblock %}" />

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{{ static_url_for('static', filename='build/main_css.bundle.css') }}"
    />

     <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap" rel="stylesheet">

    {% block css %}{% endblock %}

  </head>
  <body class="{% block body_class %}{% endblock %}">


    {% block body %} {% with form=form %} {% include "nav.html" %} {% endwith %}

    <header>{% block header %}{% endblock %}</header>

    <main role="main">
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %}
      <div class="row">
        <div class="col-md-12">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            <a class="close" title="Close" href="#" data-dismiss="alert"
              >&times;</a
            >
            {{ message }}
          </div>
          <!-- end .alert -->
          {% endfor %}
        </div>
        <!-- end col-md -->
      </div>
      <!-- end row -->
      {% endif %} {% endwith %}
      {% block content %}{% endblock %}
    </main>

    {% include "footer.html" %}

    <script src="{{ static_url_for('static', filename='build/main_js.bundle.js') }}"></script>

    {% block js %}{% endblock %}
    {% endblock %}
  </body>
</html>

hackzurich/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('public_blueprint.home') }}">
        <img src="{{static_url_for('static', filename='build/img/logo.png') }}" alt=""></a>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                                                                                              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        {% if current_user and current_user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('user_blueprint.members') }}">Challenges</a>
            </li>

            <li class="nav-item mr-auto">
                <a href="{{ url_for('public_blueprint.logout') }}"><i class="fa fa-sign-out-alt"></i> Log Out</a>
            </li>
        </ul>
        {% elif form %}
        <form class="form-inline" id="loginForm" method="POST" action="/" role="login">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <div class="input-group mb-2 mr-sm-2">
                {{ form.username(placeholder="Username", class_="form-control mr-sm-1 my-auto") }} {{ form.password(placeholder="Password",
                class_="form-control mr-sm-1 my-auto") }}
                <button class="btn btn-light btn-primary m-auto" type="submit">Login</button>
            </div>
        </form>
        <ul class="navbar-nav my-auto">
            <li class="nav-item">
                <a class="nav-link navbar-text" href="{{ url_for('public_blueprint.register') }}">Create account</a>
            </li>
        </ul>
        {% endif %}
    </div><!-- /.navbar-collapse -->
</nav>

hackzurich/templates/two_column.html
{% extends "layout.html" %}
{% block content %}

<div class="row" style="margin-bottom: 100px;background: linear-gradient(0deg, rgba(180,232,154,1) 0%, rgba(248,249,250,1) 63%);">
    <div class="col-lg-2">
    </div>
    <div class="col-lg-4 col-m-6">
        <div class="row" style="margin-top: 50px">
            <div class="col-2" id="profilePicture">
                <img  src="{{static_url_for('static', filename='build/img/profileimg.jpg') }}" style="border-radius: 50%;height: 100px">
            </div>
            <div class="col-10" style="font-size: 20pt">
                <b id="profile_username">{{ current_user.username }}</b>&emsp;vs.&emsp;{{ current_user.country }}
            </div>
        </div>
        <div style="margin-top: 50px;padding-left: 20px;padding-right: 20px">
            <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: {{ 100* total_saved_co2 / ((country_total_co2*1000)/52)}}%"
                                                                 aria-valuenow="{{total_saved_co2 }}" aria-valuemin="0" aria-valuemax="{{ (country_total_co2*1000)/52 }}"></div>
            </div>
        </div>
        <div style="text-align: center;margin-top: 50px;margin-bottom: 50px;font-size: 20pt">
            <span style="font-size: 50pt;font-weight: 500">{{ total_saved_co2|round(2) }}</span> / {{ (1000*country_total_co2/52)|round(2) }} kg CO<sub>2</sub> last week
        </div>

        <div id="accordion">
          <div class="card">
            <div class="card-header" id="headingOne">
              <h5 class="mb-0">
                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" style="color: #000">
                  Your climate balance
                </button>
              </h5>
            </div>

            <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
              <div class="card-body" style="margin-left: 10% ">
                <ul>
                    {% for done_challenge in done_challenges %}
                    <li>{{ done_challenge.done_at | datetime }} - {{ done_challenge.challenge.challengename }}: {{ done_challenge.challenge.co2offset }}</li>
                    {% endfor %}
                </ul>
                <br><b>Total saved: {{ total_saved_co2|round(2) }} kg CO<sub>2</sub></b>
              </div>
            </div>
          </div>
        </div>
    </div>
    {% block right_side %}{% endblock %}
    <div class="col-lg-2">
    </div>
</div>
{% endblock %}